version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        ClusterName: ecstatic-rabbit-seun4j  # Your ECS cluster name
        ServiceName: ecs_taskdefinition-service-nu3355aw   # Your ECS service name
        TaskDefinition: imagedefinitions:1  # ECS task definition with the revision number
        LoadBalancerInfo:
          ContainerName: myecscontainer # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
